module.exports = {
  Cargo: require("./Cargo"),
  Carro: require("./Carro"),
  CartaoChave: require("./CartaoChave"),
  Funcionario: require("./Funcionario"),
  ReservaServico: require("./ReservaServico"),
  Hospede: require("./Hospede"),
  HospedeReserva: require("./HospedeReserva"),
  LogCarro: require("./LogCarro"),
  LogQuarto: require("./LogQuarto"),
  Quarto: require("./Quarto"),
  Relato: require("./Relato"),
  Reserva: require("./Reserva"),
  Servico: require("./Servico"),
};
